name: vkapi
version: 0.0.1
description: Vk.com api implementation on Dart
author: Alexey Salnikov <me@iamsalnikov.ru>
homepage: https://github.com/iamsalnikov/vkapi.dart
dependencies:
  http: any
devDependencies:
  unittest: any